### ISSUE TITLE
小哥, 为什么自己开了一个包?

### ISSUE THREAD

**Issue by hanxu317317** [vikiboss/ck-util#1]
现在线上很多类似的包? 
例如: https://github.com/ScottHamper/Cookies

**Comment by vikiboss** [comment]
只是练手，熟悉流程

**Comment by vikiboss** [comment]
README 和 单测 基本都是 ChatGPT 写的（逃

**Comment by hanxu317317** [comment]
我擦这就有点 优秀了~

**Comment by vikiboss** [comment]
> 现在线上很多类似的包? 例如: [ScottHamper/Cookies](https://github.com/ScottHamper/Cookies)

不过也感谢你的推荐，这个之前还确实没用过，就想着自己简单写一个～

如果没其他问题，那我就 `close` 啦。
